---
title: "TempVariationwithAK"
author: "LRA"
date: "1/2/2020"
output: github_document
fig_width: 8 
fig_height: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(lubridate)
Month_order <- c("January","February","March","April","May","June","July","August","September","October","November","December")
```

```{r import and clean,include=FALSE}
WA <- read.csv("WA.2019.alltemps.csv")
OR <- read.csv("OR.alltemps.2019.csv")
BB <- read.csv("BB.alltemps.2019.csv")
AK <- read.csv("AK.2019.alltemps.csv")
All <- rbind(AK,WA,OR,BB)

All$DateObs <- as.character(All$DateObs)
All$DateObs <- as.POSIXct(All$DateObs,format="%m/%d/%y   %H:%M")
All$Day <- floor_date(All$DateObs,unit = "day")
All$Month <- floor_date(All$DateObs,unit="month")
All$Month.w <- as.character.Date(All$Month,format="%B")
All$Month.w <- ordered(All$Month.w,levels=Month_order)

Summ <- All%>%
  group_by(Region, SiteCode,SiteName,TidalHeight,Month,Month.w,Day)%>%
  summarise(DailyMean=mean(TempC),DailyMax=max(TempC),
            DailyMin=min(TempC),DailyRange=DailyMax-DailyMin,
            DailySD=sd(TempC),
            DailySE=sd(TempC)/sqrt(length(TempC)))

Summ_July <- subset(Summ,Month.w=="July")
```

## July time-series of temperature
Looking at temperatures by tidal height, site, and region, to see what drives variation in temps
```{r temp plots, echo=FALSE}
<<<<<<< HEAD
ggplot(Summ_July,aes(x=Day,y=DailyMean,color=SiteName))+geom_point(size=0.8)+
  facet_grid(rows=vars(Region),cols=vars(TidalHeight))+
  #facet_wrap(~Region+TidalHeight,nrow = 4,drop = FALSE)+
  labs(title="Daily mean temperatures in July 2019")+
  ylab("Daily mean temp (ºC)")+
  scale_x_datetime(date_breaks = "8 days",date_labels="%b %d")+
  theme_bw()+
  theme(strip.background = element_rect(fill="white"),
        legend.margin =margin(l=0,r=0,unit="mm"))
=======
ggplot(Summ_July,aes(x=Day,y=DailyMean,color=SiteName))+geom_point(size=1)+
  facet_grid(rows=vars(Region),cols=vars(TidalHeight))+
  #facet_wrap(~Region+TidalHeight,nrow = 4,drop = FALSE)+
  labs(title="Daily mean temperatures in July 2019",ylab="Daily mean temp (ºC)")+
  theme_bw()+
  theme(strip.background = element_rect(fill="white"))
>>>>>>> 1f33c96b551a1627c65f6835e84d4f0ef8688ab9

ggplot(Summ_July,aes(x=Day,y=DailyMax,color=SiteName))+geom_point(size=1)+
  facet_grid(rows=vars(Region),cols=vars(TidalHeight))+
  #facet_wrap(~Region+TidalHeight,nrow = 3)+
<<<<<<< HEAD
  labs(title="Daily maximum temperatures in July 2019")+
  ylab("Daily maximum temp (ºC)")+
  scale_x_datetime(date_breaks = "8 days",date_labels="%b %d")+
  theme_bw()+
  theme(strip.background = element_rect(fill="white"),
        legend.margin =margin(l=0,r=0,unit="mm"))

=======
  labs(title="Daily maximum temperatures in July 2019",ylab="Daily max temp (ºC)")+
  theme_bw()+
  theme(strip.background = element_rect(fill="white"))
>>>>>>> 1f33c96b551a1627c65f6835e84d4f0ef8688ab9

ggplot(Summ_July,aes(x=Day,y=DailySD,color=SiteName))+geom_point(size=1)+
  facet_grid(rows=vars(Region),cols=vars(TidalHeight))+
  #facet_wrap(~Region+TidalHeight,nrow = 3)+
<<<<<<< HEAD
  labs(title="Daily SD of temperatures in July 2019")+
  ylab("Daily SD of temp (ºC)")+
  scale_x_datetime(date_breaks = "8 days",date_labels="%b %d")+
  theme_bw()+
  theme(strip.background = element_rect(fill="white"),
        legend.margin =margin(l=0,r=0,unit="mm"))
=======
  labs(title="Daily SD of temperatures in July 2019",ylab="Daily SD (ºC)")+
  theme_bw()+
  theme(strip.background = element_rect(fill="white"))
>>>>>>> 1f33c96b551a1627c65f6835e84d4f0ef8688ab9

ggplot(Summ_July,aes(x=Day,y=DailyRange,color=SiteName))+geom_point(size=1)+
  facet_grid(rows=vars(Region),cols=vars(TidalHeight))+
  #facet_wrap(~Region+TidalHeight,nrow = 3)+
<<<<<<< HEAD
  labs(title="Daily temperature range in July 2019")+
  ylab("Daily temperature range (ºC)")+
  scale_x_datetime(date_breaks = "8 days",date_labels="%b %d")+
  theme_bw()+
  theme(strip.background = element_rect(fill="white"),
        legend.margin =margin(l=0,r=0,unit="mm"))
=======
  labs(title="Daily temperature range in July 2019",ylab="Daily temp range (ºC)")+
  theme_bw()+
  theme(strip.background = element_rect(fill="white"))
>>>>>>> 1f33c96b551a1627c65f6835e84d4f0ef8688ab9

```